export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";

export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAILURE = "FETCH_SERVICES_FAILURE";

export const FETCH_SERVICE_REQUEST = "FETCH_SERVICE_REQUEST";
export const FETCH_SERVICE_SUCCESS = "FETCH_SERVICE_SUCCESS";
export const FETCH_SERVICE_FAILURE = "FETCH_SERVICE_FAILURE";

export const SAVE_SERVICE_REQUEST = "SAVE_SERVICE_REQUEST";
export const SAVE_SERVICE_SUCCESS = "SAVE_SERVICE_SUCCESS";
export const SAVE_SERVICE_FAILURE = "SAVE_SERVICE_FAILURE";

export const REMOVE_SERVICE_REQUEST = "REMOVE_SERVICE_REQUEST";
export const REMOVE_SERVICE_SUCCESS = "REMOVE_SERVICE_SUCCESS";
export const REMOVE_SERVICE_FAILURE = "REMOVE_SERVICE_FAILURE";
